server:
  env_name: ${APP_ENV:openai}

llm:
  mode: openai

embedding:
  mode: openai

openai:
  api_key: ${OPENAI_API_KEY:sk-proj-vWD78qmcaehUe7OujJq0T3BlbkFJDskVYJeN38gqmaeh14nj}
  model: gpt-3.5-turbo
